# Generated by Django 5.0.3 on 2024-04-05 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('superpower', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='comic',
            name='characters',
            field=models.ManyToManyField(to='main_app.character'),
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Rating Date')),
                ('rating', models.CharField(choices=[('E', 'Excellent'), ('G', 'Good'), ('F', 'Fair')], default='E', max_length=1)),
                ('comic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.comic')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
